In [1]:
import pandas as pd

calls = pd.read_csv("../data/options/SPY_Calls.csv")

calls.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,SPY260806C00630000,2026-08-05 18:08:22+00:00,630.0,141.86,0.0,0.0,0.0,0.0,1.0,1,0.00001,True,REGULAR,USD
1,SPY260806C00675000,2026-07-30 14:47:04+00:00,675.0,63.40,0.0,0.0,0.0,0.0,NaN,0,0.00001,True,REGULAR,USD
2,SPY260806C00680000,2026-08-05 19:59:32+00:00,680.0,90.70,0.0,0.0,0.0,0.0,10.0,8,0.00001,True,REGULAR,USD
3,SPY260806C00685000,2026-07-27 15:32:15+00:00,685.0,54.90,0.0,0.0,0.0,0.0,1.0,1,0.00001,True,REGULAR,USD
4,SPY260806C00700000,2026-08-03 14:23:19+00:00,700.0,54.45,0.0,0.0,0.0,0.0,2.0,1,0.00001,True,REGULAR,USD

In [2]:
filtered_calls = calls[
    (calls["openInterest"] >= 100) &
    (calls["volume"] >= 10)
].copy()

In [3]:
filtered_calls[
    [
        "strike",
        "lastPrice",
        "impliedVolatility",
        "volume",
        "openInterest"
    ]
].head(10)

    strike  lastPrice  impliedVolatility  volume  openInterest
28   735.0      36.37            0.00001    11.0           185
31   738.0      33.31            0.00001    12.0           698
33   740.0      31.98            0.00001    33.0          3156
35   742.0      27.78            0.00001    17.0           912
36   743.0      28.48            0.00001    13.0           466
37   744.0      28.32            0.00001    22.0           731
38   745.0      25.11            0.00001    52.0          1622
39   746.0      24.95            0.00001    17.0          2217
41   748.0      22.40            0.00001   157.0          1322
42   749.0      22.82            0.00001    18.0           748

In [4]:
filtered_calls["IV %"] = filtered_calls["impliedVolatility"] * 100

filtered_calls[
    [
        "strike",
        "IV %"
    ]
].head(10)

    strike   IV %
28   735.0  0.001
31   738.0  0.001
33   740.0  0.001
35   742.0  0.001
36   743.0  0.001
37   744.0  0.001
38   745.0  0.001
39   746.0  0.001
41   748.0  0.001
42   749.0  0.001

In [5]:
print(
    "Average IV:",
    filtered_calls["IV %"].mean()
)

Average IV: 5.621603515625

In [6]:
print(
    "Highest IV:",
    filtered_calls["IV %"].max()
)

Highest IV: 25.00075

In [7]:
print(
    "Lowest IV:",
    filtered_calls["IV %"].min()
)

Lowest IV: 0.0010000000000000005

In [8]:
filtered_calls.nlargest(
    5,
    "impliedVolatility"
)[
    [
        "strike",
        "IV %"
    ]
]

    strike      IV %
90   810.0  25.00075
91   815.0  25.00075
92   820.0  25.00075
93   825.0  25.00075
94   830.0  25.00075

In [9]:
filtered_calls.nsmallest(
    5,
    "impliedVolatility"
)[
    [
        "strike",
        "IV %"
    ]
]

    strike   IV %
28   735.0  0.001
31   738.0  0.001
33   740.0  0.001
35   742.0  0.001
36   743.0  0.001

In [10]:
filtered_calls.to_csv("../data/options/SPY_IVfiltered_calls.csv", index=False)